import type { Metadata } from "next";
import "@/styles/global.css";

import { AppSidebar } from "@/components/ui-custom/layout/private/Sidebar";
import { SidebarProvider } from "@/components/ui/sidebar"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function privateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <SidebarProvider>
        <AppSidebar />
        <main className="flex-1">{children}</main>
      </SidebarProvider>
    </div>
  );
}
