import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Guests Pages",
  description: "Generated by create next app",
};

// SaaS Conversion Pages
export default function GuestLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <main>
    {children}
   </main>
  );
}
